### ISSUE TITLE
does not work in a modal

### ISSUE THREAD

**Issue by seiyria** [zefoy/ngx-color-picker#29] opened 2017-06-17 16:31 UTC
same issue reported here: https://github.com/Alberplz/angular2-color-picker/issues/109

**Comment by sconix** [comment] 2017-06-18 12:09
Not sure what mean, why would you need to use it with modal. Maybe I am not understanding correctly. Possible to make a Plunker example?

**Comment by seiyria** [comment] 2017-06-18 13:57
My edit interface is in a modal.

**Comment by wartab** [comment] 2017-06-18 23:10
@sconix In a project I am no longer working on, we used Bootstrap modals. One of those modals asked for further configuration of the user profile before continuing in a form. One of those configuration inputs was a color picker. IIRC, when using a color picker in a modal, the z-index of the modal is higher than the color picker selector. We worked around that by setting an !important flag to a higher z-index.

**Comment by sconix** [comment] 2017-06-19 12:02
Ok so its just a styling issue, well not sure if this is actually a bug. There will always be situations that some other library styles conflict with other libs, but I will add a higher z-index for next release to hopefully avoid more issues.

**Comment by seiyria** [comment] 2017-06-19 12:47
In my case it's offset to the right and none of the styling attributes seem
to work.

**Comment by sconix** [comment] 2017-06-19 15:56
Without Plunker or some sort of ready example there is not much to do. Even with example no quarantees if this can be made to work out of the box since with other custom elements there is always the change that some styles need to be overwritten or custom js code needed.

**Comment by JakobSegerslatt** [comment] 2017-06-26 09:55
It could be z-index issues but it can also be overflow: hidden on a parent element (which you want to ignore). My fix was wrap your colorpicker-input in a wrapper div/span and set it to position: relative and the underlyiung colopicker to position: fixed.

css
`
.colorpicker-parent {
position: relative;
}
color-picker {
position: fixed
}
`
html
`
<span class="colorpicker-parent">
<input [(colorPicker)]="myValue">
</span>
`

**Comment by sconix** [comment] 2017-07-03 20:33
Thanks for the info, I will take this into account when doing the code re-factoring / improvments. Hopefully I can get this play bit nicer with modals etc.

**Comment by jbiversen** [comment] 2017-07-05 07:28
I have the same problem with bootstrap modal. Here is a plunker to illustrate the problem:

https://plnkr.co/edit/rhgCVdn8vplOke0dNsft

JakobSegerslatt trick doesn't seem to help either.

**Comment by JakobSegerslatt** [comment] 2017-07-05 08:49
@jbiversen I tried your plunker i chrome, ff and edge but the colorpicker in the modal works in all of them? Did you find a solution?

**Comment by jbiversen** [comment] 2017-07-05 08:55
@JakobSegerslatt That is odd. This is how it looks like in edge (in the plunker example)

![image](https://user-images.githubusercontent.com/29895629/27856967-23c8055e-6170-11e7-969f-2dd24d8ca35c.png)

Chrome looks the same

Edge version: 40.15063.0.0
Chrome version: 58.0.3029.110 (64-bit)

**Comment by JakobSegerslatt** [comment] 2017-07-05 09:16
My bad, i opened the plunker with a small width, and thus i didn't see that it was incorrectly placed.

Your problem can be quickly fixed with css though until a more permanent fix is in placed.
`
.modal-dialog input {
position: relative;
}

.modal-dialog .color-picker {
  position: absolute !important;
  left: 310px !important;
  top: 56px !important;
}
`

**Comment by sconix** [comment] 2017-07-05 09:20
Thanks for the Plunker example, I will try and see if I can include some changes for the next release which makes manual css tweaking unnecessary.

**Comment by sconix** [comment] 2017-07-05 14:00
I looked this bit more closely and the reason why position is incorrect is that the modal uses transform. That causes the fixed position to "break". 

I will add a new option 'popover' for cpDialogDisplay which makes color picker position the dialog with absolute position relative to the container. At least I can't think of any other solution since I am not aware of any way to get the actual viewport location for the position fixed.

**Comment by Valstorm** [comment] 2017-07-06 15:39
I've been having the same issue with nesting the color picker component inside another element that is uses position: fixed and is not positioned top left, due to relative offset.
Would it be possible to pass through a selector such as an ID or class to the component to target the container element that the color picker dialog gets appended to?

Great work btw.

**Comment by sconix** [comment] 2017-07-06 19:37
Well passing ID / selector would not be that easy to use or it at least requires more manual work to find the element which defines the viewport. I think the popover mode should work nicely for those situations where dialog is used inside "special" components so lets try that first and if it wont work then lets think this more :).

I am still finishing the popover mode and once its done I will release 4.1.0. Hopefully tomorrow, but if I don't manage then it goes to Monday/Tuesday.

**Comment by sconix** [comment] 2017-07-06 19:39
Appending the dialog to the document body would work nicely, but I don't like that idea so much since for example in our case our application can be embedded into any webpage and if we start adding components to the document body there will be problems :) Of course there could be always some special mode which would do that, but as said lets try if the popover / absolute positioning will solve the problem.

**Comment by Valstorm** [comment] 2017-07-06 22:24
Suggestion for an option of appending the color-picker dialog to the document body would be to resolve other modal related issues, overflow: hidden on parent component for example is quite a common scenario for modals or scroll-able components. If the component has the option to receive the target element ID or selector to append the component to I feel this would allow users more control over small layout problems that are difficult to resolve without modifying/overriding the color-picker layout CSS.

I agree that in some circumstances it may not be possible to know the parent document structure for nested apps, but a unique ID or selector would be a welcome addition for edge cases and is also quite a common implementation with 'popover' dialog components.

Thanks, I'll give the changes pushed into 4.1.0 a go and see if that resolves the issue I have at the moment.

**Comment by sconix** [comment] 2017-07-07 09:58
I hope to get the popover ready today, and I will look into your suggestion that if the code structure allows that easily I could add that next week.

**Comment by sconix** [comment] 2017-07-10 17:14
I looked into the adding the component into body or given id selector and I did not find an easy way to do it. What I can do is to add a possibility to create the component on the same level as the applications root component, this should be enough I think. I will add this to 4.1.0 which should be out tomorrow in addition to the popover absolute positioning.

**Comment by sconix** [comment] 2017-07-11 07:02
I also think that I managed to change the position calculation so that it can find elements with transform and calculate the fixed position relative to those. So there will be now 3 different ways to position the dialog which all should work with modals, but most likely at least one will work :)

**Comment by sconix** [comment] 2017-07-11 08:16
I just verified that both cpUseRootViewContainer and the default popup positioning now works with the provided Plunker example. I will release 4.1.0 now and if there are situations where the positioning fails I can do additional tweaks if somebody provides with Plunker example that shows the problem.

**Comment by Valstorm** [comment] 2017-07-12 08:19
I've tried [cpUseRootViewContainer]="true"

The openDialog method still injects the component into the host element that has the directive rather than my app root component.

Stepping through this code:
https://github.com/zefoy/ngx-color-picker/blob/master/src/lib/color-picker.directive.ts#L103

In my app the `appInstance = this.injector.get(classOfRootComponent);` is returning an empty object, see below:
![image](https://user-images.githubusercontent.com/1510130/28108265-40f16274-672e-11e7-99ce-2673f317c34d.png)

Have I missed something?

**Comment by sconix** [comment] 2017-07-12 08:40
I should add a console log for that, the way angular works atm is that you need to expose the viewContainerRef in the root component so add public viewContainerRef: ViewContainerRef to the root component constructor. The name can be either viewContainerRef or vcRef. Then color picker can access the viewContainerRef of the root component.

Of course that wont help if the injector get is returning empty object, are you sure about that? At least the same code was used in other libs as well and I tested with the example app and the Plunker example and it did work. The documentation is next to none when it comes to getting root component, but this method was used in few places so it should be valid.

**Comment by Valstorm** [comment] 2017-07-13 02:35
Ah that worked, thanks @sconix!

As you mentioned I needed to inject `public viewContainerRef: ViewContainerRef` in my app root constructor. It would be helpful to mention this in the documentation for that option.

Did the original angular 1 component have any positioning logic to determine whether it should anchor the color picker dialog at the top or the bottom depending on the space available in the viewport?

**Comment by sconix** [comment] 2017-07-13 07:35
I picked this library after it was left unmaintained I am not even aware of if this is based on any Angular 1 component. But yeah there would be nice to have some automatic logic to the positioning so that window limits are taken into account and I plan to add such things at some point. Also the automatic closing when scroll is detected would be nice, but that is already quite easy to add yourself so its not top of my list.

I hope to make a code cleanup / improvements during this summer and with that most likely I will add some polishing features such as the positioning improvements. At the latest I try to do this when Angular 5 is out.

I will improve the documentation and will add a console warning about the missing viewContainerRef. Its bit sad that Angular does not offer any "automatic" way to get the viewContainerRef.

**Comment by Valstorm** [comment] 2017-07-13 09:55
I mentioned the lack of a decent color picker to @robwormald a few weeks ago in Slack, the community agreed that this one would be perfect 
https://casesandberg.github.io/react-color/
*nudge nudge*

**Comment by sconix** [comment] 2017-07-13 10:51
Ok good to have some benchmark :) Although I don't plan to add different dialog layouts (at least not atm), only want to make the default be as usable as possible, but PR's are always accepted if somebody wants to add different layouts etc.

**Closed** 2017-07-24 07:09 UTC

**Comment by hoicwu2** [comment] 2017-08-08 11:24
I am using ngx-bootstrap modal and the ngx-color-picker
I have already set both the ViewContainerRef and cpUseRootViewContainer. 
I got the error ExpressionChangedAfterItHasBeenCheckedError when I tried to open the modal and pick a color for a second time.

Main Actions
1. Open modal
2. Pick a color from color-picker
3. Close the modal
4. Pick a color again from color-picker
5. ExpressionChangedAfterItHasBeenCheckedError is thrown

<img width="1403" alt="screen shot 2017-08-08 at 6 59 29 pm" src="https://user-images.githubusercontent.com/23411242/29069630-453ad22a-7c6e-11e7-881b-a0dd4307aa0a.png">

Do you have any idea on the issue?
Thanks.

**Comment by sconix** [comment] 2017-08-08 15:16
Are you using onPush? Not sure what could cause it, but I can try to reproduce the problem. Of course it might be also your app doing something funky, but it looks bit like issue within color picker.

**Comment by marcj** [comment] 2018-03-03 18:36
Got the same issue as @hoicwu2 and really don't do anything special.

**Comment by marcj** [comment] 2018-03-03 18:43
Ok, I checked again and the error appears only  happens only when I use `[cpUseRootViewContainer]="true"`.

It happens basically when the value inside `[colorPicker]="page.backgroundColor"` changed from outside, like when some method would do:

```
public changeColorToWhite() {
    this.page.backgroundColor = '#ffffff';
}
```

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: 3'. Current value: 'ngIf: false'.
    at viewDebugError (core.js:9771)
    at expressionChangedAfterItHasBeenCheckedError (core.js:9749)
    at checkBindingNoChanges (core.js:9916)
    at checkNoChangesNodeInline (core.js:13964)
    at checkNoChangesNode (core.js:13938)
    at debugCheckNoChangesNode (core.js:14767)
    at debugCheckDirectivesFn (core.js:14669)
    at Object.eval [as updateDirectives] (ColorPickerComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14651)
    at checkNoChangesView (core.js:13776)
View_ColorPickerComponent_0 @ ColorPickerComponent.html:1
proxyClass @ compiler.js:14653
DebugContext_.logError @ core.js:14992
ErrorHandler.handleError @ core.js:1509
(anonymous) @ core.js:5910
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4693
ApplicationRef.tick @ core.js:5910
(anonymous) @ core.js:5736
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4745
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4562
next @ core.js:5736
schedulerFn @ core.js:4327
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4307
checkStable @ core.js:4710
onLeave @ core.js:4789
onInvokeTask @ core.js:4739
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
```
