### ISSUE TITLE
Question: How to enter value for the color picker using Angular Material Input

### ISSUE THREAD

**Issue by FathyV** [zefoy/ngx-color-picker#136] opened 2018-08-30 08:55 UTC
Hi,
Currently I'm using the `Angular Material` and `ngx-color-picker` for my project. However, I found that I won't be able to enter the value of the color inside the color picker.
It seems having some problem with the `mat-form-field`. Whenever I click on the color picker, the input field is focused right after that.
I wonder is there a way to work around? Thank you for your support.

*Update:
Here is an example of the issue that I'm encounter.
https://stackblitz.com/edit/test-ngx-color-picker?file=src%2Fapp%2Fapp.module.ts

**Comment by sconix** [comment] 2018-09-02 08:34
So what are you after, that the input field would not be focused? If input field is meant to be used by the user shouldn't it get focus?

**Comment by FathyV** [comment] 2018-10-26 03:58
@sconix Sorry for response this late. There is a case want to enter the value instead but as you can see in my example. Whenever you clicked on the input field it immediately loose focus. Since this only happen when using angular material. I wonder is the a workaround to handle this issue.
![2018-10-26_105652](https://user-images.githubusercontent.com/21316352/47543741-eb488200-d90d-11e8-93f6-30562db459a0.png)

**Comment by sconix** [comment] 2018-10-26 08:43
Anyway you could set up an minimal reproduction in Stackblitz? This sounds strange, but its possible that there is a bug in this library.

**Comment by sconix** [comment] 2018-10-26 08:57
Now I see the problem. Let me look into this bit more to see if there is an issue in this library or this is something else.

**Comment by wartab** [comment] 2018-10-26 09:37
The explanation is pretty simple: 

mat-form-field has a click event attached to it that will call onContainerClicked() on the form-control element if you click the mat-form-field element. (https://github.com/angular/material2/blob/master/src/lib/input/input.ts#L404)
The matInput directive gives the form-control the focus if you click while not having the focus (https://github.com/angular/material2/blob/master/src/lib/input/input.ts#L404).

Since the color picker is added inside mat-form-field (and not added as a independent overlay), this click event handler is triggered.

Untested, but I think the simplest approach would be to attach a click event handler to the color picker with `event.stopPropagation();`

**Comment by sconix** [comment] 2018-10-26 09:42
I just tested and this is the case. I have added catching of the click event so this will be fixed on the 7.0.0 release happening on Sunday.

**Closed** 2018-10-26 09:43 UTC
Labels: question
