### ISSUE TITLE
Error on pasting text to input field

### ISSUE THREAD

**Issue by aleics** [zefoy/ngx-color-picker#79] opened 2017-11-10 12:40 UTC
Hello! I've been using your library and I've found a bug that makes the application crash. When pasting a text into the input field, the`ColorPickerDirective` crashes on accessing a variable of an undefined object:

![screen shot 2017-11-10 at 13 36 04](https://user-images.githubusercontent.com/6661743/32658934-93b71894-c61c-11e7-8507-b8e1e3cd43e3.png)

For the moment, I prevent the crash by adding a `readonly` attribute to the input element, so the user will not use this input, but the one of the color-picker itself.

**Comment by sconix** [comment] 2017-11-10 12:44
What version of the library you have? It looks like some old bug has made it back.

**Comment by sconix** [comment] 2017-11-14 19:15
Could you also share your configuration and tell me does the color picker open when you focus the input field.

**Comment by sconix** [comment] 2017-11-25 11:06
Will close this for now, I would need a way to reproduce this to fix it. This also might be fixed by the latest changes.

**Closed by sconix** 2017-11-25 11:06 UTC
